-- =====================================================
-- DATABASE: TANAH SUCI - Travel Haji & Umrah
-- Author: Generated by AI
-- Date: 2024
-- Description: Database lengkap untuk website Tanah Suci
--              dengan kemampuan custom semua konten
-- =====================================================
-- CATATAN INFINITYFREE: 
-- Database sudah dibuat oleh hosting dengan nama: if0_40794045_tanah_suci_db
-- Import file ini langsung ke phpMyAdmin InfinityFree
-- =====================================================

-- =====================================================
-- TABEL: site_settings
-- Fungsi: Pengaturan umum website (nama, logo, warna, dll)
-- =====================================================
CREATE TABLE IF NOT EXISTS site_settings (  
    id INT AUTO_INCREMENT PRIMARY KEY,
    setting_key VARCHAR(100) NOT NULL UNIQUE COMMENT 'Kunci pengaturan (unik)',
    setting_value TEXT COMMENT 'Nilai pengaturan',
    setting_type ENUM('text', 'textarea', 'image', 'color', 'url', 'number') DEFAULT 'text' COMMENT 'Tipe input',
    setting_group VARCHAR(50) DEFAULT 'general' COMMENT 'Grup pengaturan (general, hero, footer, dll)',
    setting_label VARCHAR(100) COMMENT 'Label tampilan di admin',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Pengaturan umum website';

-- Data default site_settings
INSERT INTO site_settings (setting_key, setting_value, setting_type, setting_group, setting_label) VALUES
-- General Settings
('site_name', 'TanahSuci', 'text', 'general', 'Nama Website'),
('site_name_highlight', 'Suci', 'text', 'general', 'Nama Website (Highlight Gold)'),
('site_tagline', 'Perjalanan Ibadah Premium', 'text', 'general', 'Tagline Website'),
('site_description', 'Wujudkan impian ibadah Umrah dan Haji Anda dengan layanan premium dan syar''i bersama Tanah Suci.', 'textarea', 'general', 'Deskripsi Website'),
('site_logo', '', 'image', 'general', 'Logo Website'),
('primary_color', '#0F172A', 'color', 'general', 'Warna Utama'),
('accent_color', '#D4AF37', 'color', 'general', 'Warna Aksen (Gold)'),

-- Hero Section
('hero_title_line1', 'Menuju Baitullah', 'text', 'hero', 'Hero Judul Baris 1'),
('hero_title_line2', 'Dengan Ketenangan Hati', 'text', 'hero', 'Hero Judul Baris 2'),
('hero_subtitle', 'Layanan perjalanan ibadah Umrah dan Haji premium, membimbing langkah Anda menuju tanah suci dengan kenyamanan dan kekhusyukan.', 'textarea', 'hero', 'Hero Deskripsi'),
('hero_background_image', 'https://images.unsplash.com/photo-1565552629477-ff1459bb5a7f?q=80&w=2670&auto=format&fit=crop', 'image', 'hero', 'Hero Background Image'),
('hero_btn_primary_text', 'Lihat Paket', 'text', 'hero', 'Tombol Utama Hero'),
('hero_btn_primary_link', '#packages', 'url', 'hero', 'Link Tombol Utama'),
('hero_btn_secondary_text', 'Konsultasi Gratis', 'text', 'hero', 'Tombol Sekunder Hero'),
('hero_btn_secondary_link', 'konsultasi.php', 'url', 'hero', 'Link Tombol Sekunder'),

-- About Section
('about_subtitle', 'Mengapa Memilih Kami', 'text', 'about', 'About Subtitle'),
('about_title', 'Melayani Tamu Allah', 'text', 'about', 'About Judul'),
('about_title_highlight', 'Sepenuh Hati', 'text', 'about', 'About Judul (Highlight Gold)'),
('about_description', 'Kami berdedikasi untuk memberikan pengalaman ibadah terbaik dengan fasilitas bintang lima dan bimbingan sesuai sunnah.', 'textarea', 'about', 'About Deskripsi'),

-- CTA Section
('cta_title', 'Siap Menjadi Tamu Allah?', 'text', 'cta', 'CTA Judul'),
('cta_description', 'Konsultasikan rencana ibadah Anda bersama kami. Insya Allah kami bantu wujudkan perjalanan spiritual yang tak terlupakan.', 'textarea', 'cta', 'CTA Deskripsi'),
('cta_button_text', 'Chat WhatsApp', 'text', 'cta', 'CTA Tombol Teks'),
('cta_whatsapp_number', '', 'text', 'cta', 'Nomor WhatsApp'),

-- Packages Section
('packages_subtitle', 'Pilihan Paket', 'text', 'packages', 'Paket Subtitle'),
('packages_title', 'Paket', 'text', 'packages', 'Paket Judul'),
('packages_title_highlight', 'Umrah & Haji', 'text', 'packages', 'Paket Judul (Highlight Gold)');

-- =====================================================
-- TABEL: navigation_menu
-- Fungsi: Menu navigasi website (bisa ditambah/edit/hapus)
-- =====================================================
CREATE TABLE IF NOT EXISTS navigation_menu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    menu_label VARCHAR(100) NOT NULL COMMENT 'Nama menu yang ditampilkan',
    menu_link VARCHAR(255) NOT NULL COMMENT 'Link tujuan menu',
    menu_order INT DEFAULT 0 COMMENT 'Urutan tampilan menu',
    is_button TINYINT(1) DEFAULT 0 COMMENT '1 = tampil sebagai button, 0 = tampil sebagai link biasa',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Menu navigasi website';

-- Data default navigation_menu
INSERT INTO navigation_menu (menu_label, menu_link, menu_order, is_button, is_active) VALUES
('Beranda', '#hero', 1, 0, 1),
('Tentang Kami', '#about', 2, 0, 1),
('Paket Umrah', '#packages', 3, 0, 1),
('Galeri', '#gallery', 4, 0, 1),
('Hubungi Kami', '#contact', 5, 1, 1);

-- =====================================================
-- TABEL: features
-- Fungsi: Section "Mengapa Memilih Kami" (feature cards)
-- =====================================================
CREATE TABLE IF NOT EXISTS features (
    id INT AUTO_INCREMENT PRIMARY KEY,
    icon VARCHAR(100) NOT NULL COMMENT 'Font Awesome icon class',
    title VARCHAR(150) NOT NULL COMMENT 'Judul fitur',
    description TEXT NOT NULL COMMENT 'Deskripsi fitur',
    link_url VARCHAR(255) DEFAULT '#' COMMENT 'Link detail fitur',
    link_text VARCHAR(100) DEFAULT 'Baca Selengkapnya' COMMENT 'Teks link',
    feature_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    delay_class VARCHAR(20) DEFAULT '' COMMENT 'CSS class untuk delay animasi',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Fitur/keunggulan layanan';

-- Data default features
INSERT INTO features (icon, title, description, link_url, link_text, feature_order, delay_class, is_active) VALUES
('fa-solid fa-hotel', 'Akomodasi Premium', 'Hotel bintang 5 dekat dengan Masjidil Haram dan Masjid Nabawi untuk kenyamanan ibadah Anda.', 'article.php?slug=akomodasi-premium', 'Baca Selengkapnya', 1, '', 1),
('fa-solid fa-kaaba', 'Bimbingan Syar''i', 'Dibimbing oleh Ustadz berpengalaman dan tersertifikasi untuk menjamin keabsahan ibadah.', 'article.php?slug=bimbingan-syari', 'Baca Selengkapnya', 2, 'delay-1', 1),
('fa-solid fa-plane-departure', 'Penerbangan Langsung', 'Menggunakan maskapai terbaik dengan rute direct flight untuk efisiensi waktu perjalanan.', 'article.php?slug=penerbangan-langsung', 'Baca Selengkapnya', 3, 'delay-2', 1);



-- =====================================================
-- TABEL: packages
-- Fungsi: Paket Umrah dan Haji
-- =====================================================
CREATE TABLE IF NOT EXISTS packages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL COMMENT 'Nama paket',
    price VARCHAR(50) NOT NULL COMMENT 'Harga paket (format: Rp 35.000.000)',
    currency VARCHAR(10) DEFAULT 'Rp' COMMENT 'Mata uang',
    duration VARCHAR(50) COMMENT 'Durasi paket (contoh: 9 Hari)',
    image_url VARCHAR(255) COMMENT 'URL gambar paket',
    tag VARCHAR(50) COMMENT 'Tag/label (contoh: Most Popular)',
    button_text VARCHAR(100) DEFAULT 'Pesan Sekarang' COMMENT 'Teks tombol CTA',
    button_link VARCHAR(255) DEFAULT '#contact' COMMENT 'Link tombol CTA',
    package_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    delay_class VARCHAR(20) DEFAULT '' COMMENT 'CSS class untuk delay animasi',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Paket umrah dan haji';

-- Data default packages
INSERT INTO packages (name, price, currency, duration, image_url, tag, button_text, button_link, package_order, delay_class, is_active) VALUES
('Umrah Premium 9 Hari', '35.000.000', 'Rp', '9 Hari', 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?q=80&w=2670&auto=format&fit=crop', 'Most Popular', 'Pesan Sekarang', '#contact', 1, '', 1),
('Umrah Plus Turki 12 Hari', '42.500.000', 'Rp', '12 Hari', 'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=80&w=2670&auto=format&fit=crop', NULL, 'Pesan Sekarang', '#contact', 2, 'delay-1', 1),
('Haji Furoda (Tanpa Antri)', '24.500', '$', NULL, 'https://images.unsplash.com/photo-1533757704860-384affeed946?q=80&w=2670&auto=format&fit=crop', NULL, 'Konsultasi Haji', '#contact', 3, 'delay-2', 1);

-- =====================================================
-- TABEL: package_features
-- Fungsi: Fitur-fitur di dalam setiap paket
-- =====================================================
CREATE TABLE IF NOT EXISTS package_features (
    id INT AUTO_INCREMENT PRIMARY KEY,
    package_id INT NOT NULL COMMENT 'ID paket (foreign key)',
    feature_text VARCHAR(255) NOT NULL COMMENT 'Teks fitur',
    feature_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (package_id) REFERENCES packages(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Fitur-fitur di dalam paket';

-- Data default package_features
INSERT INTO package_features (package_id, feature_text, feature_order, is_active) VALUES
-- Paket 1: Umrah Premium 9 Hari
(1, 'Hotel Bintang 5 (0 meter)', 1, 1),
(1, 'Saudia Airlines Direct', 2, 1),
(1, 'Makan Fullboard Menu Indonesia', 3, 1),
(1, 'Bus AC Executive Terbaru', 4, 1),
-- Paket 2: Umrah Plus Turki 12 Hari
(2, 'Wisata Halal Istanbul & Bursa', 1, 1),
(2, 'Hotel Bintang 5 & 4', 2, 1),
(2, 'Turkish Airlines', 3, 1),
(2, 'Tour Guide Professional', 4, 1),
-- Paket 3: Haji Furoda
(3, 'Visa Haji Furoda Resmi', 1, 1),
(3, 'Maktab VIP Arafah Mina', 2, 1),
(3, 'Hotel Bintang 5 Depan Masjid', 3, 1),
(3, 'Dokter Pendamping Khusus', 4, 1);

-- =====================================================
-- TABEL: gallery
-- Fungsi: Galeri gambar
-- =====================================================
CREATE TABLE IF NOT EXISTS gallery (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(255) NOT NULL COMMENT 'URL gambar',
    alt_text VARCHAR(255) COMMENT 'Teks alternatif gambar',
    caption VARCHAR(255) COMMENT 'Keterangan gambar',
    gallery_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Galeri gambar website';

-- =====================================================
-- TABEL: footer_links
-- Fungsi: Link di footer (navigasi dan layanan)
-- =====================================================
CREATE TABLE IF NOT EXISTS footer_links (
    id INT AUTO_INCREMENT PRIMARY KEY,
    section VARCHAR(50) NOT NULL COMMENT 'Seksi footer (navigasi, layanan)',
    link_label VARCHAR(100) NOT NULL COMMENT 'Label link',
    link_url VARCHAR(255) NOT NULL COMMENT 'URL tujuan',
    link_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Link di footer';

-- Data default footer_links
INSERT INTO footer_links (section, link_label, link_url, link_order, is_active) VALUES
-- Navigasi
('navigasi', 'Beranda', '#hero', 1, 1),
('navigasi', 'Tentang Kami', '#about', 2, 1),
('navigasi', 'Paket', '#packages', 3, 1),
('navigasi', 'Galeri', '#gallery', 4, 1),
-- Layanan
('layanan', 'Umrah Reguler', '#', 1, 1),
('layanan', 'Umrah Plus', '#', 2, 1),
('layanan', 'Haji Khusus', '#', 3, 1),
('layanan', 'Haji Furoda', '#', 4, 1);

-- =====================================================
-- TABEL: contact_info
-- Fungsi: Informasi kontak di footer
-- =====================================================
CREATE TABLE IF NOT EXISTS contact_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    icon VARCHAR(100) NOT NULL COMMENT 'Font Awesome icon class',
    info_type VARCHAR(50) NOT NULL COMMENT 'Tipe info (address, phone, email)',
    info_value TEXT NOT NULL COMMENT 'Nilai kontak',
    info_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Informasi kontak';

-- Data default contact_info
INSERT INTO contact_info (icon, info_type, info_value, info_order, is_active) VALUES
('fa-solid fa-location-dot', 'address', 'Jl. Sultan Iskandar Muda No. 8, Jakarta Selatan', 1, 1),
('fa-solid fa-phone', 'phone', '+62 21 7890 1234', 2, 1),
('fa-regular fa-envelope', 'email', 'info@tanahsuci.com', 3, 1);

-- =====================================================
-- TABEL: social_media
-- Fungsi: Link social media
-- =====================================================
CREATE TABLE IF NOT EXISTS social_media (
    id INT AUTO_INCREMENT PRIMARY KEY,
    platform VARCHAR(50) NOT NULL COMMENT 'Nama platform (instagram, facebook, dll)',
    icon VARCHAR(100) NOT NULL COMMENT 'Font Awesome icon class',
    url VARCHAR(255) NOT NULL COMMENT 'URL profil',
    social_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Link social media';

-- Data default social_media
INSERT INTO social_media (platform, icon, url, social_order, is_active) VALUES
('instagram', 'fa-brands fa-instagram', '#', 1, 1),
('facebook', 'fa-brands fa-facebook-f', '#', 2, 1),
('youtube', 'fa-brands fa-youtube', '#', 3, 1),
('tiktok', 'fa-brands fa-tiktok', '#', 4, 1);

-- =====================================================
-- TABEL: footer_info
-- Fungsi: Informasi tambahan footer (izin, copyright)
-- =====================================================
CREATE TABLE IF NOT EXISTS footer_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    info_key VARCHAR(100) NOT NULL UNIQUE COMMENT 'Kunci informasi',
    info_value TEXT COMMENT 'Nilai informasi',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Informasi footer';

-- Data default footer_info
INSERT INTO footer_info (info_key, info_value) VALUES
('brand_description', 'Penyelenggara Perjalanan Ibadah Umrah & Haji Khusus yang terpercaya dan amanah.'),
('license_info', 'Izin Resmi Kemenag No. 123/2024'),
('copyright_text', '© 2024 Tanah Suci Travel. All Rights Reserved.'),
('created_by', 'Amrina Farza'),
('contact_address', 'Jl. Sultan Iskandar Muda No. 8, Kebayoran Lama, Jakarta Selatan 12240'),
('contact_phone', '+62 812-3456-7890'),
('contact_email', 'info@tanahsuci.com'),
('contact_whatsapp', '+62 812-3456-7890');


-- =====================================================
-- TABEL: testimonials
-- Fungsi: Testimoni pelanggan
-- =====================================================
CREATE TABLE IF NOT EXISTS testimonials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL COMMENT 'Nama pelanggan',
    customer_photo VARCHAR(255) COMMENT 'URL foto pelanggan',
    package_name VARCHAR(150) COMMENT 'Nama paket yang diambil',
    testimonial_text TEXT NOT NULL COMMENT 'Isi testimoni',
    rating INT DEFAULT 5 COMMENT 'Rating 1-5',
    testimonial_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Testimoni pelanggan';

-- Data default testimonials
INSERT INTO testimonials (customer_name, customer_photo, package_name, testimonial_text, rating, testimonial_order, is_active) VALUES
('Hj. Siti Aminah', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=150', 'Paket Umrah Premium', 'Alhamdulillah, perjalanan umrah bersama TanahSuci sangat berkesan. Pelayanan prima, hotel dekat dengan Masjidil Haram, dan pembimbing yang sangat sabar. Jazakallahu khairan!', 5, 1, 1),
('H. Ahmad Fauzan', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150', 'Paket Umrah Reguler', 'Sudah 2 kali umrah dengan TanahSuci, dan selalu puas dengan pelayanannya. Manasik yang intensif membuat ibadah lebih khusyuk. Insya Allah akan berangkat lagi tahun depan.', 5, 2, 1),
('Keluarga Bpk. Rudi', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=150', 'Paket Umrah Keluarga', 'Berangkat sekeluarga besar 12 orang, semua diurus dengan baik. Anak-anak juga dibimbing dengan sabar. Terima kasih TanahSuci!', 5, 3, 1),
('Ibu Fatimah', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=150', 'Paket Umrah Premium', 'MasyaAllah, pengalaman spiritual yang luar biasa. Hotel sangat dekat, hanya beberapa langkah ke Masjidil Haram. Pembimbing ustadz sangat membantu.', 5, 4, 1);


-- =====================================================
-- TABEL: admins
-- Fungsi: Akun admin untuk login panel admin
-- =====================================================
CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE COMMENT 'Username login',
    password VARCHAR(255) NOT NULL COMMENT 'Password (hashed)',
    full_name VARCHAR(100) COMMENT 'Nama lengkap',
    email VARCHAR(100) UNIQUE COMMENT 'Email admin',
    avatar VARCHAR(255) DEFAULT NULL COMMENT 'Foto profil admin',
    role ENUM('super_admin', 'admin', 'editor') DEFAULT 'admin' COMMENT 'Role admin',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    remember_token VARCHAR(255) DEFAULT NULL COMMENT 'Token untuk remember me',
    token_expires TIMESTAMP NULL COMMENT 'Waktu expired token',
    last_login TIMESTAMP NULL COMMENT 'Waktu login terakhir',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Akun admin';

-- Data default admin (password: admin123)
INSERT INTO admins (username, password, full_name, email, role, is_active) VALUES
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Super Admin', 'admin@tanahsuci.com', 'super_admin', 1);

-- =====================================================
-- TABEL: admin_logs
-- Fungsi: Log aktivitas admin
-- =====================================================
CREATE TABLE IF NOT EXISTS admin_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    admin_id INT NOT NULL COMMENT 'ID admin',
    action VARCHAR(100) NOT NULL COMMENT 'Aksi yang dilakukan',
    description TEXT COMMENT 'Deskripsi aksi',
    ip_address VARCHAR(45) COMMENT 'IP Address',
    user_agent TEXT COMMENT 'Browser/User Agent',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='Log aktivitas admin';

-- =====================================================
-- TABEL: page_sections
-- Fungsi: Section tambahan yang bisa dikustom (general purpose)
-- =====================================================
CREATE TABLE IF NOT EXISTS page_sections (
    id INT AUTO_INCREMENT PRIMARY KEY,
    page_name VARCHAR(100) NOT NULL COMMENT 'Nama halaman (home, about, dll)',
    section_name VARCHAR(100) NOT NULL COMMENT 'Nama section',
    section_title VARCHAR(255) COMMENT 'Judul section',
    section_subtitle VARCHAR(255) COMMENT 'Subtitle section',
    section_content TEXT COMMENT 'Konten section',
    section_image VARCHAR(255) COMMENT 'Gambar section',
    section_order INT DEFAULT 0 COMMENT 'Urutan tampilan',
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = nonaktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Section halaman yang bisa dikustom';

-- =====================================================
-- TABEL: subscribers
-- Fungsi: Daftar subscriber/newsletter
-- =====================================================
CREATE TABLE IF NOT EXISTS subscribers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE COMMENT 'Email subscriber',
    name VARCHAR(100) COMMENT 'Nama subscriber',
    subscribed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active TINYINT(1) DEFAULT 1 COMMENT '1 = aktif, 0 = unsubscribe'
) ENGINE=InnoDB COMMENT='Daftar subscriber';

-- =====================================================
-- TABEL: inquiries
-- Fungsi: Form kontak/pertanyaan dari pengunjung
-- =====================================================
CREATE TABLE IF NOT EXISTS inquiries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL COMMENT 'Nama pengirim',
    email VARCHAR(100) NOT NULL COMMENT 'Email pengirim',
    phone VARCHAR(20) COMMENT 'Nomor telepon',
    subject VARCHAR(255) COMMENT 'Subjek pesan',
    message TEXT NOT NULL COMMENT 'Isi pesan',
    package_interest INT COMMENT 'ID paket yang diminati (foreign key)',
    status ENUM('new', 'read', 'replied', 'closed') DEFAULT 'new' COMMENT 'Status pesan',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (package_interest) REFERENCES packages(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='Pertanyaan/kontak dari pengunjung';

-- =====================================================
-- TABEL: articles
-- Fungsi: Halaman artikel/konten dinamis
-- =====================================================
DROP TABLE IF EXISTS articles;
CREATE TABLE articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE COMMENT 'URL slug (contoh: akomodasi-premium)',
    title VARCHAR(200) NOT NULL COMMENT 'Judul artikel',
    title_highlight VARCHAR(100) COMMENT 'Bagian judul yang di-highlight (gold)',
    subtitle VARCHAR(255) COMMENT 'Subtitle di hero section',
    hero_image VARCHAR(500) COMMENT 'URL gambar hero background',
    content_image VARCHAR(500) COMMENT 'URL gambar di content section',
    content_title VARCHAR(200) COMMENT 'Judul konten utama',
    content_text TEXT COMMENT 'Teks paragraf utama',
    features_json TEXT COMMENT 'JSON array untuk list fitur [{icon, title, desc}]',
    cards_section_title VARCHAR(100) COMMENT 'Judul section kartu (opsional)',
    cards_section_subtitle VARCHAR(100) COMMENT 'Subtitle section kartu',
    cards_json TEXT COMMENT 'JSON array untuk kartu [{image, title, location, rating}]',
    cta_title VARCHAR(200) COMMENT 'Judul CTA section',
    cta_text VARCHAR(255) COMMENT 'Teks CTA section',
    meta_description VARCHAR(255) COMMENT 'Meta description untuk SEO',
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB COMMENT='Halaman artikel dinamis';

-- Data default articles
INSERT INTO articles (slug, title, title_highlight, subtitle, hero_image, content_image, content_title, content_text, features_json, cards_section_title, cards_section_subtitle, cards_json, cta_title, cta_text, meta_description) VALUES
('akomodasi-premium', 'Akomodasi', 'Premium', 'Hotel bintang 5 dengan lokasi strategis dekat Masjidil Haram dan Masjid Nabawi', 
 'https://images.unsplash.com/photo-1590076215667-875d4ef2d7de?q=80&w=2000',
 'https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=800',
 'Kenyamanan Terbaik untuk Ibadah Anda',
 'Kami menyediakan akomodasi hotel bintang 5 yang terletak sangat dekat dengan Masjidil Haram di Makkah dan Masjid Nabawi di Madinah. Dengan jarak tempuh hanya beberapa langkah, Anda dapat fokus beribadah tanpa kelelahan.\n\nSetiap kamar dilengkapi dengan fasilitas modern dan pelayanan prima untuk memastikan kenyamanan Anda selama berada di Tanah Suci.',
 '[{"icon":"fa-solid fa-location-dot","title":"Lokasi Strategis","desc":"Hotel berjarak 0-50 meter dari Masjidil Haram dan Masjid Nabawi"},{"icon":"fa-solid fa-bed","title":"Kamar Mewah","desc":"Kamar luas dengan tempat tidur nyaman dan pemandangan indah"},{"icon":"fa-solid fa-utensils","title":"Makan Fullboard","desc":"Menu Indonesia halal dengan variasi masakan internasional"},{"icon":"fa-solid fa-wifi","title":"Fasilitas Lengkap","desc":"WiFi gratis, laundry, dan room service 24 jam"}]',
 'Hotel', 'Partner Hotel',
 '[{"image":"https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=600","title":"Hilton Suites Makkah","location":"50m dari Masjidil Haram","rating":5},{"image":"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=600","title":"Pullman Zamzam Madinah","location":"Depan Masjid Nabawi","rating":5},{"image":"https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=600","title":"Fairmont Makkah Clock Tower","location":"View langsung Ka''bah","rating":5}]',
 'Siap Menikmati Akomodasi Terbaik?', 'Hubungi kami untuk informasi lebih lanjut tentang hotel dan paket perjalanan',
 'Hotel bintang 5 dekat Masjidil Haram dan Masjid Nabawi untuk kenyamanan ibadah Anda.'),

('bimbingan-syari', 'Bimbingan', 'Syar''i', 'Dibimbing oleh Ustadz berpengalaman dan tersertifikasi untuk menjamin keabsahan ibadah',
 'https://images.unsplash.com/photo-1564769625905-50e93615e769?q=80&w=2000',
 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?q=80&w=800',
 'Ibadah yang Benar Sesuai Sunnah',
 'Kami memahami bahwa ibadah Umrah dan Haji adalah ibadah yang sangat spesial. Oleh karena itu, kami menyediakan pembimbing yang berpengalaman dengan ilmu agama mendalam.',
 '[{"icon":"fa-solid fa-book-quran","title":"Manasik Intensif","desc":"Pelatihan 3x sebelum keberangkatan"},{"icon":"fa-solid fa-users","title":"Rasio Pembimbing Ideal","desc":"1 Pembimbing : 25 jamaah"},{"icon":"fa-solid fa-clock","title":"Bimbingan 24 Jam","desc":"Pembimbing selalu siap mendampingi"},{"icon":"fa-solid fa-certificate","title":"Tersertifikasi Kemenag","desc":"Semua pembimbing resmi"}]',
 'Ustadz', 'Tim Pembimbing',
 '[{"image":"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400","title":"Ustadz Dr. Ahmad Fauzi, Lc., M.A.","location":"Pembimbing Senior - Lulusan Al-Azhar","rating":5},{"image":"https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=400","title":"Ustadz Hasan Basri, Lc.","location":"Pembimbing Utama - Hafidz 30 Juz","rating":5},{"image":"https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400","title":"Ustadz Muhammad Ridwan, S.Ag.","location":"Spesialis jamaah lansia","rating":5}]',
 'Siap Beribadah dengan Bimbingan Terbaik?', 'Konsultasikan kebutuhan ibadah Anda bersama tim kami',
 'Dibimbing oleh Ustadz berpengalaman dan tersertifikasi untuk menjamin keabsahan ibadah.'),

('penerbangan-langsung', 'Penerbangan', 'Langsung', 'Maskapai terbaik dengan rute direct flight untuk efisiensi dan kenyamanan perjalanan',
 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=2000',
 'https://images.unsplash.com/photo-1569154941061-e231b4725ef1?q=80&w=800',
 'Terbang Nyaman Menuju Tanah Suci',
 'Kami bekerja sama dengan maskapai penerbangan terbaik untuk memberikan pengalaman terbang yang nyaman dan efisien. Dengan penerbangan langsung (direct flight), Anda tidak perlu transit dan dapat tiba di Tanah Suci dengan kondisi prima.',
 '[{"icon":"fa-solid fa-plane","title":"Direct Flight","desc":"Penerbangan langsung tanpa transit"},{"icon":"fa-solid fa-chair","title":"Kursi Nyaman","desc":"Legroom luas dan kursi recline"},{"icon":"fa-solid fa-utensils","title":"Inflight Meal","desc":"Makanan halal berkualitas"},{"icon":"fa-solid fa-suitcase","title":"Bagasi Besar","desc":"Hingga 30kg + 7kg kabin"}]',
 'Maskapai', 'Partner Maskapai',
 '[{"image":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Saudia_logo.svg/200px-Saudia_logo.svg.png","title":"Saudia Airlines","location":"Maskapai resmi Arab Saudi dengan layanan premium","rating":5},{"image":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Garuda_Indonesia_Logo.svg/200px-Garuda_Indonesia_Logo.svg.png","title":"Garuda Indonesia","location":"Kebanggaan Indonesia dengan layanan bintang 5","rating":5},{"image":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Turkish_Airlines_logo_2019_compact.svg/200px-Turkish_Airlines_logo_2019_compact.svg.png","title":"Turkish Airlines","location":"Untuk paket Umrah Plus via Istanbul","rating":5}]',
 'Siap Terbang ke Tanah Suci?', 'Hubungi kami untuk informasi jadwal penerbangan dan ketersediaan seat',
 'Maskapai terbaik dengan rute direct flight untuk efisiensi dan kenyamanan perjalanan.');

-- Update features link_url to use article.php?slug=
UPDATE features SET link_url = 'article.php?slug=akomodasi-premium' WHERE link_url LIKE '%akomodasi%';
UPDATE features SET link_url = 'article.php?slug=bimbingan-syari' WHERE link_url LIKE '%bimbingan%';
UPDATE features SET link_url = 'article.php?slug=penerbangan-langsung' WHERE link_url LIKE '%penerbangan%';

-- =====================================================
-- INDEX untuk optimasi query
-- =====================================================
CREATE INDEX idx_settings_group ON site_settings(setting_group);
CREATE INDEX idx_features_order ON features(feature_order);
CREATE INDEX idx_packages_order ON packages(package_order);
CREATE INDEX idx_gallery_order ON gallery(gallery_order);
CREATE INDEX idx_footer_links_section ON footer_links(section);
CREATE INDEX idx_inquiries_status ON inquiries(status);
CREATE INDEX idx_articles_slug ON articles(slug);

